import { useState } from "react";

const lessons = [
  {
    id: 1,
    emoji: "\ud83d\udd24",
    title: "Kores Alifbosi",
    subtitle: "Hangul (\ud55c\uae00)",
    color: "#6366f1",
    light: "#eef2ff",
    sections: [
      {
        type: "info",
        title: "\ud83d\udccc Dars maqsadi",
        items: [
          "Barcha kores undosh va unli harflarni o'rganish",
          "Bo'g'in tuzilishini tushunish (\ubc1b\uce68 \u2014 batchim)",
          "Oddiy so'zlarni o'qish va yozishni mashq qilish",
        ],
      },
      {
        type: "text",
        title: "1. Hangul tarixi",
        content: "Hangul \u2014 Koreya yozuvi bo'lib, 1443-yilda qirol Sejong (\uc138\uc885\ub300\uc655) tomonidan yaratilgan. Bu dunyodagi eng ilmiy va o'rganish oson alifbolardan biri. Hangulda har bir harf alohida emas, balki bo'g'in (syllable) shaklida yoziladi.",
      },
      {
        type: "table",
        title: "2. Undosh harflar (\uc790\uc74c \u2014 Jaeum)",
        headers: ["Harf", "Talaffuz", "Misol", "Ma'nosi"],
        rows: [
          ["\u3131", "G/K", "\uac00\uad6c (gagu)", "mebel"],
          ["\u3134", "N", "\ub098\ubb34 (namu)", "daraxt"],
          ["\u3137", "D/T", "\ub2e4\ub9ac (dari)", "ko'prik"],
          ["\u3139", "R/L", "\ub77c\uba74 (ramyon)", "lapsha"],
          ["\u3141", "M", "\ub9c8\uc74c (maeum)", "yurak"],
          ["\u3142", "B/P", "\ubc14\ub2e4 (bada)", "dengiz"],
          ["\u3145", "S", "\uc0ac\ub78c (saram)", "odam"],
          ["\u3147", "Tovushsiz/NG", "\uc544\uc774 (ai)", "bola"],
          ["\u3148", "J", "\uc790\ub2e4 (jada)", "uxlamoq"],
          ["\u314a", "Ch", "\ucc28 (cha)", "choy/mashina"],
          ["\u314b", "K (kuchli)", "\uce74\ud398 (kape)", "kafe"],
          ["\u314c", "T (kuchli)", "\ud0c0\ub2e4 (tada)", "minmoq"],
          ["\u314d", "P (kuchli)", "\ud30c\ub2e4 (pada)", "qazmoq"],
          ["\u314e", "H", "\ud558\ub2e4 (hada)", "qilmoq"],
        ],
      },
      {
        type: "table",
        title: "\ud83d\udd34 Qo'shaloq undoshlar (\uc30d\uc790\uc74c)",
        headers: ["Harf", "Talaffuz", "Misol", "Ma'nosi"],
        rows: [
          ["\u3132", "KK (qattiq)", "\uae4c\ub2e4 (kkada)", "qiyin/artmoq"],
          ["\u3138", "TT (qattiq)", "\ub530\ub2e4 (ttada)", "uzib olmoq"],
          ["\u3143", "PP (qattiq)", "\ube60\ub974\ub2e4 (ppareuda)", "tez"],
          ["\u3146", "SS (qattiq)", "\uc2f8\ub2e4 (ssada)", "arzon"],
          ["\u3149", "JJ (qattiq)", "\uc9dc\ub2e4 (jjada)", "sho'r"],
        ],
      },
      {
        type: "table",
        title: "3. Unli harflar (\ubaa8\uc74c \u2014 Moeum)",
        headers: ["Harf", "Talaffuz", "Izoh"],
        rows: [
          ["\u314f", "A", "O'zbekcha 'a' kabi"],
          ["\u3153", "Eo", "O'zbekcha 'o' ga yaqin"],
          ["\u3157", "O", "Lab yumalanib aytiladi"],
          ["\u315c", "U", "Lab oldinga cho'ziladi"],
          ["\u3161", "Eu", "Labsiz 'u' \u2014 o'zbekchada yo'q"],
          ["\u3163", "I", "O'zbekcha 'i' kabi"],
          ["\u3150", "Ae", "E ga juda yaqin"],
          ["\u3154", "E", "O'zbekcha 'e' kabi"],
          ["\u3151", "Ya", "ya+a"],
          ["\u3155", "Yeo", "y+eo"],
          ["\u315b", "Yo", "y+o"],
          ["\u3160", "Yu", "y+u"],
        ],
      },
      {
        type: "box",
        color: "#fef9c3",
        border: "#eab308",
        title: "\ud83d\udca1 \ubc1b\uce68 (Batchim) nima?",
        content: "Batchim \u2014 bo'g'inning eng pastidagi undosh harf. Masalan: \ubc25 (bap)da \u3142 batchim. Batchim talaffuzga kuchli ta'sir qiladi: \ubc25\uc774\uc5d0\uc694 (babieyo) \u2014 \u3142 keyingi bo'g'inga o'tib ketadi!",
      },
      {
        type: "table",
        title: "4. Ko'p ishlatiladigan so'zlar",
        headers: ["Kores", "Talaffuz", "Ma'nosi"],
        rows: [
          ["\ubb3c", "mul", "suv"],
          ["\ubc25", "bap", "guruch / ovqat"],
          ["\uc0ac\ub78c", "saram", "odam, kishi"],
          ["\ud55c\uad6d", "hanguk", "Koreya"],
          ["\ud559\uad50", "hakkyo", "maktab"],
          ["\uc0ac\ub791", "sarang", "sevgi"],
          ["\uce5c\uad6c", "chingu", "do'st"],
          ["\uc120\uc0dd\ub2d8", "seonsaengnim", "o'qituvchi"],
          ["\uac00\uc871", "gajok", "oila"],
          ["\ub098\ub77c", "nara", "mamlakat"],
        ],
      },
      {
        type: "practice",
        title: "\ud83d\udcdd Mashqlar",
        items: [
          "Harflarni o'qing: \uac00\ub098\ub2e4\ub77c\ub9c8\ubc14\uc0ac\uc544\uc790\ucc28\uce74\ud0c0\ud30c\ud558",
          "Unlilarni o'qing: \uc544\uc57c\uc5b4\uc5ec\uc624\uc694\uc6b0\uc720\uc73c\uc774",
          "\uc0ac\ub791 = sa+rang = sevgi",
          "\ud55c\uad6d = han+guk = Koreya",
          "\ubb3c = mul = suv",
        ],
      },
      {
        type: "check",
        title: "\u2705 Nazorat savollari",
        items: [
          "Barcha 14 undoshni bilaman",
          "5 qo'shaloq undoshni bilaman",
          "Barcha unlilarni bilaman",
          "Bo'g'in tuzilishini tushundim",
          "10 ta so'zni o'qiy olaman",
        ],
      },
    ],
  },
  {
    id: 2,
    emoji: "\ud83d\udc4b",
    title: "Salomlashish",
    subtitle: "\uc778\uc0ac\ud558\uae30",
    color: "#ec4899",
    light: "#fdf2f8",
    sections: [
      {
        type: "info",
        title: "\ud83d\udccc Dars maqsadi",
        items: [
          "Rasmiy va norasmiy salomlashishni o'rganish",
          "O'zini tanishtira olish",
          "Kasb, millat va yosh haqida gapirishni o'rganish",
        ],
      },
      {
        type: "table",
        title: "1. Salomlashish iboralari (\uc778\uc0ac\ub9d0)",
        headers: ["Kores", "Talaffuz", "Ma'nosi"],
        rows: [
          ["\uc548\ub155\ud558\uc138\uc694", "annyeonghaseyo", "Salom (rasmiy)"],
          ["\uc548\ub155\ud788 \uac00\uc138\uc694", "annyeonghi gaseyo", "Xayr (ketayotganga)"],
          ["\uc548\ub155\ud788 \uacc4\uc138\uc694", "annyeonghi gyeseyo", "Xayr (qolayotganga)"],
          ["\uc548\ub155", "annyeong", "Salom/Xayr (norasmiy)"],
          ["\ucc98\uc74c \ubd59\uaca0\uc2b5\ub2c8\ub2e4", "cheoeum boepgesseumnida", "Birinchi marta uchrashuv"],
          ["\ubc18\uac11\uc2b5\ub2c8\ub2e4", "bangapseumnida", "Tanishganimdan xursandman"],
          ["\uc798 \uc9c0\ub0c8\uc5b4\uc694?", "jal jinaesseoyo?", "Qandaysiz? (rasmiy)"],
          ["\uac10\uc0ac\ud569\ub2c8\ub2e4", "gamsahamnida", "Rahmat (rasmiy)"],
          ["\uace0\ub9d9\uc2b5\ub2c8\ub2e4", "gomapseumnida", "Rahmat (oddiy)"],
          ["\ucc9c\ub9cc\uc5d0\uc694", "cheonmane yo", "Iltimos"],
        ],
      },
      {
        type: "dialog",
        title: "2. Tanishish dialogi",
        lines: [
          { speaker: "A", text: "\uc548\ub155\ud558\uc138\uc694! \ucc98\uc74c \ubd59\uaca0\uc2b5\ub2c8\ub2e4.", translation: "Salom! Birinchi marta ko'rishyapmiz." },
          { speaker: "B", text: "\uc548\ub155\ud558\uc138\uc694! \uc800\ub294 \uae40\ubbfc\uc900\uc785\ub2c8\ub2e4.", translation: "Salom! Men Kim Minjunman." },
          { speaker: "A", text: "\ubc18\uac11\uc2b5\ub2c8\ub2e4. \uc800\ub294 \uc544\ud750\ub9c8\ub4dc\uc608\uc694.", translation: "Tanishganimdan xursandman. Men Akhmadman." },
          { speaker: "B", text: "\uc5b4\ub290 \ub098\ub77c \uc0ac\ub78c\uc774\uc5d0\uc694?", translation: "Qaysi mamlakatdansiz?" },
          { speaker: "A", text: "\uc800\ub294 \uc6b0\uc988\ubca0\ud0a4\uc2a4\ud0c4 \uc0ac\ub78c\uc774\uc5d0\uc694.", translation: "Men O'zbekistonlikman." },
        ],
      },
      {
        type: "table",
        title: "3. Mamlakat va millat nomlari",
        headers: ["Mamlakat", "Kores", "Talaffuz"],
        rows: [
          ["O'zbekiston", "\uc6b0\uc988\ubca0\ud0a4\uc2a4\ud0c4", "Ujeubekiseuran"],
          ["Koreya", "\ud55c\uad6d", "Hanguk"],
          ["Amerika", "\ubbf8\uad6d", "Miguk"],
          ["Rossiya", "\ub7ec\uc2dc\uc544", "Reosia"],
          ["Xitoy", "\uc911\uad6d", "Jungguk"],
          ["Yaponiya", "\uc77c\ubcf8", "Ilbon"],
        ],
      },
      {
        type: "table",
        title: "4. Kasb nomlari",
        headers: ["Kasb", "Kores", "Talaffuz"],
        rows: [
          ["Talaba", "\ud559\uc0dd", "haksaeng"],
          ["O'qituvchi", "\uc120\uc0dd\ub2d8", "seonsaengnim"],
          ["Shifokor", "\uc758\uc0ac", "uisa"],
          ["Muhandis", "\uc5d4\uc9c0\ub2c8\uc5b4", "enjinieo"],
          ["Oshpaz", "\uc694\ub9ac\uc0ac", "yorisa"],
          ["Biznesmen", "\uc0ac\uc5c5\uac00", "sa'eobga"],
        ],
      },
      {
        type: "box",
        color: "#eff6ff",
        border: "#3b82f6",
        title: "\ud83d\udcd6 Grammatika: \uc774\uc5d0\uc694 / \uc608\uc694",
        content: "Undosh + \uc774\uc5d0\uc694: \ud559\uc0dd\uc774\uc5d0\uc694 (Talaba\u043c\u0430\u043d)\nUnli + \uc608\uc694: \uc758\uc0ac\uc608\uc694 (Shifokorman)\n\uc800\ub294 + [ism] + \uc774\uc5d0\uc694/\uc608\uc694: \uc800\ub294 \uc544\ud750\ub9c8\ub4dc\uc608\uc694 (Men Akhmadman)",
      },
      {
        type: "check",
        title: "\u2705 Nazorat savollari",
        items: [
          "10 ta salomlashish iborasini bilaman",
          "O'zimni kores tilida tanishtira olaman",
          "Kasb va millat so'zlarini bilaman",
          "\uc774\uc5d0\uc694/\uc608\uc694 grammatikasini tushundim",
        ],
      },
    ],
  },
  {
    id: 3,
    emoji: "\ud83d\udd22",
    title: "Sonlar va Sanash",
    subtitle: "\uc22b\uc790\uc640 \uc138\uae30",
    color: "#10b981",
    light: "#ecfdf5",
    sections: [
      {
        type: "info",
        title: "\ud83d\udccc Dars maqsadi",
        items: [
          "Sino-kores va tub kores sonlarini o'rganish",
          "Ulardan qachon foydalanishni tushunish",
          "Narx, telefon raqam, yosh, sana aytishni o'rganish",
        ],
      },
      {
        type: "table",
        title: "1. Sino-kores sonlari (\ud55c\uc790\uc5b4 \uc22b\uc790)",
        headers: ["Son", "Kores", "Talaffuz"],
        rows: [
          ["0", "\uc601/\uacf5", "yeong/gong"],
          ["1", "\uc77c", "il"],
          ["2", "\uc774", "i"],
          ["3", "\uc0bc", "sam"],
          ["4", "\uc0ac", "sa"],
          ["5", "\uc624", "o"],
          ["6", "\uc721", "yuk"],
          ["7", "\uce60", "chil"],
          ["8", "\ud314", "pal"],
          ["9", "\uad6c", "gu"],
          ["10", "\uc2ed", "sip"],
          ["100", "\ubc31", "baek"],
          ["1,000", "\ucc9c", "cheon"],
          ["10,000", "\ub9cc", "man"],
        ],
      },
      {
        type: "table",
        title: "2. Tub kores sonlari (\uace0\uc720\uc5b4 \uc22b\uc790)",
        headers: ["Son", "Kores", "Talaffuz"],
        rows: [
          ["1", "\ud558\ub098", "hana"],
          ["2", "\ub458", "dul"],
          ["3", "\uc14b", "set"],
          ["4", "\ub137", "net"],
          ["5", "\ub2e4\uc12f", "daseot"],
          ["6", "\uc5ec\uc12f", "yeoseot"],
          ["7", "\uc77c\uacf1", "ilgop"],
          ["8", "\uc5ec\ub35f", "yeodeol"],
          ["9", "\uc544\ud649", "ahop"],
          ["10", "\uc5f4", "yeol"],
          ["20", "\uc2a4\ubb3c", "seumul"],
          ["30", "\uc11c\ub978", "seoreun"],
          ["40", "\ub9c8\ud754", "maheun"],
          ["50", "\uc270", "swin"],
        ],
      },
      {
        type: "box",
        color: "#fff7ed",
        border: "#f97316",
        title: "\u26a0\ufe0f Muhim qoida!",
        content: "Tub kores sonlari + sanash so'z qo'shilganda 1-4 o'zgaradi:\nhana \u2192 han, dul \u2192 du, set \u2192 se, net \u2192 ne\nMasalan: \ud55c \uac1c (1 ta dona), \ub450 \uba85 (2 kishi), \uc138 \uc2dc (3 soat)",
      },
      {
        type: "table",
        title: "3. Sanash so'zlari (\ub2e8\uc704\uba85\uc0ac)",
        headers: ["So'z", "Talaffuz", "Nima uchun", "Misol"],
        rows: [
          ["\uac1c", "gae", "Narsalar (dona)", "\uc0ac\uacfc \ub450 \uac1c \u2014 2 ta olma"],
          ["\uba85", "myeong", "Odamlar", "\ud559\uc0dd \uc138 \uba85 \u2014 3 nafar"],
          ["\ub9c8\ub9ac", "mari", "Hayvonlar", "\uace0\uc591\uc774 \ud55c \ub9c8\ub9ac \u2014 1 mushuk"],
          ["\uad8c", "gwon", "Kitoblar", "\ucc45 \ub2e4\uc12f \uad8c \u2014 5 kitob"],
          ["\uc794", "jan", "Ichimliklar", "\ucee4\ud53c \ub450 \uc794 \u2014 2 stakan"],
          ["\ubcd1", "byeong", "Butilkalar", "\ubb3c \ud55c \ubcd1 \u2014 1 butilka"],
          ["\uc0b4", "sal", "Yosh", "\uc2a4\ubb3c \uc0b4 \u2014 20 yosh"],
          ["\uce35", "cheung", "Qavat", "\uc0bc \uce35 \u2014 3-qavat"],
        ],
      },
      {
        type: "check",
        title: "\u2705 Nazorat savollari",
        items: [
          "1-100 gacha sino-kores sonlarni bilaman",
          "1-99 gacha tub kores sonlarni bilaman",
          "8 ta sanash so'zini bilaman",
          "Narx aytishni bilaman",
        ],
      },
    ],
  },
  {
    id: 4,
    emoji: "\u23f0",
    title: "Vaqt va Kunlar",
    subtitle: "\uc2dc\uac04\uacfc \uc77c\uacfc",
    color: "#f59e0b",
    light: "#fffbeb",
    sections: [
      {
        type: "info",
        title: "\ud83d\udccc Dars maqsadi",
        items: [
          "Soat aytish va so'rashni o'rganish",
          "Kun, oy, yil nomlarini o'rganish",
          "Kundalik tartibotni kores tilida ifodalash",
        ],
      },
      {
        type: "table",
        title: "1. Soat aytish",
        headers: ["Vaqt", "Kores", "Talaffuz"],
        rows: [
          ["Soat 1:00", "\ud55c \uc2dc", "han si"],
          ["Soat 2:30", "\ub450 \uc2dc \uc0bc\uc2ed \ubd84", "du si samsip bun"],
          ["Soat 3:15", "\uc138 \uc2dc \uc2ed\uc624 \ubd84", "se si sipo bun"],
          ["Soat 6:45", "\uc5ec\uc12f \uc2dc \uc0ac\uc2ed\uc624 \ubd84", "yeoseot si sasipo bun"],
          ["Soat 12:00", "\uc5f4\ub450 \uc2dc", "yeoldu si"],
          ["Tong (AM)", "\uc624\uc804", "ojeon"],
          ["Kechqurun (PM)", "\uc624\ud6c4", "ohu"],
        ],
      },
      {
        type: "table",
        title: "2. Hafta kunlari (\uc694\uc77c)",
        headers: ["Kun", "Kores", "Talaffuz"],
        rows: [
          ["Dushanba", "\uc6d4\uc694\uc77c", "woryoil"],
          ["Seshanba", "\ud654\uc694\uc77c", "hwayoil"],
          ["Chorshanba", "\uc218\uc694\uc77c", "suyoil"],
          ["Payshanba", "\ubaa9\uc694\uc77c", "mogyoil"],
          ["Juma", "\uae08\uc694\uc77c", "geumyoil"],
          ["Shanba", "\ud1a0\uc694\uc77c", "toyoil"],
          ["Yakshanba", "\uc77c\uc694\uc77c", "iryoil"],
        ],
      },
      {
        type: "table",
        title: "3. Oy nomlari (\uc6d4)",
        headers: ["Oy", "Kores", "Talaffuz"],
        rows: [
          ["Yanvar", "1\uc6d4", "irwol"],
          ["Fevral", "2\uc6d4", "iwol"],
          ["Mart", "3\uc6d4", "samwol"],
          ["Aprel", "4\uc6d4", "sawol"],
          ["May", "5\uc6d4", "owol"],
          ["Iyun", "6\uc6d4", "yuwol"],
          ["Iyul", "7\uc6d4", "chirwol"],
          ["Avgust", "8\uc6d4", "parwol"],
          ["Sentabr", "9\uc6d4", "guwol"],
          ["Oktabr", "10\uc6d4", "siwol"],
          ["Noyabr", "11\uc6d4", "sibirwol"],
          ["Dekabr", "12\uc6d4", "sibiwol"],
        ],
      },
      {
        type: "table",
        title: "4. Vaqt ifodalari",
        headers: ["Ma'nosi", "Kores", "Talaffuz"],
        rows: [
          ["Bugun", "\uc624\ub298", "oneul"],
          ["Ertaga", "\ub0b4\uc77c", "naeil"],
          ["Indinga", "\ubaa8\ub808", "more"],
          ["Kecha", "\uc5b4\uc81c", "eoje"],
          ["Shu hafta", "\uc774\ubc88 \uc8fc", "ibeon ju"],
          ["Keyingi hafta", "\ub2e4\uc74c \uc8fc", "daeum ju"],
          ["O'tgan hafta", "\uc9c0\ub09c \uc8fc", "jinan ju"],
        ],
      },
      {
        type: "dialog",
        title: "5. Kundalik tartib namunasi",
        lines: [
          { speaker: "6:00", text: "\uc77c\uc5b4\ub098\uc694", translation: "Turaman" },
          { speaker: "7:00", text: "\uc544\uce68\uc744 \uba39\uc5b4\uc694", translation: "Nonushta qilaman" },
          { speaker: "8:00", text: "\ud559\uad50\uc5d0 \uac00\uc694", translation: "Maktabga boraman" },
          { speaker: "12:00", text: "\uc810\uc2ec\uc744 \uba39\uc5b4\uc694", translation: "Tushlik qilaman" },
          { speaker: "22:00", text: "\uc790\uc694", translation: "Uxlayman" },
        ],
      },
      {
        type: "check",
        title: "\u2705 Nazorat savollari",
        items: [
          "Soat aytishni bilaman",
          "Hafta kunlarini bilaman",
          "Oy nomlarini bilaman",
          "Kundalik tartibotni ifodalay olaman",
        ],
      },
    ],
  },
  {
    id: 5,
    emoji: "\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc66",
    title: "Oila A'zolari",
    subtitle: "\uac00\uc871",
    color: "#8b5cf6",
    light: "#f5f3ff",
    sections: [
      {
        type: "info",
        title: "\ud83d\udccc Dars maqsadi",
        items: [
          "Oila a'zolari nomlarini o'rganish",
          "Oila haqida gaplashishni o'rganish",
          "Rasmiy va norasmiy murojaat shakllarini tushunish",
        ],
      },
      {
        type: "table",
        title: "1. Oila a'zolari nomlari",
        headers: ["A'zo", "O'z oilam", "Boshqa oila (hurmatli)"],
        rows: [
          ["Ota", "\uc544\ubc84\uc9c0", "\uc544\ubc84\ub2d8"],
          ["Ona", "\uc5b4\uba38\ub2c8", "\uc5b4\uba38\ub2d8"],
          ["Aka (erkak)", "\ud615", "\ud615\ub2d8"],
          ["Opa (erkak)", "\ub204\ub098", "\ub204\ub2d8"],
          ["Aka (ayol)", "\uc624\ube60", "\uc624\ub77c\ubc84\ub2c8"],
          ["Opa (ayol)", "\uc5b8\ub2c8", "\uc5b8\ub2c8"],
          ["Uka/Singil", "\ub3d9\uc0dd", "\ub3d9\uc0dd"],
          ["Buva", "\ud560\uc544\ubc84\uc9c0", "\ud560\uc544\ubc84\ub2d8"],
          ["Buvi", "\ud560\uba38\ub2c8", "\ud560\uba38\ub2d8"],
          ["Er", "\ub0a8\ud3b8", "\ub0a8\ud3b8\ubd84"],
          ["Xotin", "\uc544\ub0b4", "\ubd80\uc778"],
          ["O'g'il", "\uc544\ub4e4", "\uc544\ub4dc\ub2d8"],
          ["Qiz", "\ub538", "\ub530\ub2d8"],
        ],
      },
      {
        type: "dialog",
        title: "2. Oila haqida dialog",
        lines: [
          { speaker: "A", text: "\uac00\uc871\uc774 \uba87 \uba85\uc774\uc5d0\uc694?", translation: "Oilangizda necha kishi bor?" },
          { speaker: "B", text: "\ub124 \uba85\uc774\uc5d0\uc694. \uc544\ubc84\uc9c0, \uc5b4\uba38\ub2c8, \ud615, \uadf8\ub9ac\uace0 \uc800\uc608\uc694.", translation: "4 kishi. Otam, onam, akam va men." },
          { speaker: "A", text: "\ud615\uc774 \uba87 \uc0b4\uc774\uc5d0\uc694?", translation: "Akangiz necha yoshda?" },
          { speaker: "B", text: "\uc2a4\ubb3c\uc5ec\ub35f \uc0b4\uc774\uc5d0\uc694.", translation: "Yigirma sakkiz yoshda." },
        ],
      },
      {
        type: "practice",
        title: "3. Oila haqida foydali gaplar",
        items: [
          "\uc800\ub294 \uc678\ub3d9\ub538\uc774\uc5d0\uc694 \u2014 Men yolg'iz qizman",
          "\uc800\ub294 \ub9c9\ub0b4\uc608\uc694 \u2014 Men eng kichik farzandman",
          "\uc800\ub294 \uc7a5\ub0a8\uc774\uc5d0\uc694 \u2014 Men katta o'g'ilman",
          "\ubd80\ubaa8\ub2d8\uc740 \uc11c\uc6b8\uc5d0 \uc0ac\uc138\uc694 \u2014 Ota-onam Seulda yashaydi",
          "\uac00\uc871\uc774 \uba87 \uba85\uc774\uc5d0\uc694? \u2014 Oilangizda necha kishi?",
        ],
      },
      {
        type: "check",
        title: "\u2705 Nazorat savollari",
        items: [
          "Barcha oila a'zolari nomlarini bilaman",
          "Oila haqida qisqacha gapirishni bilaman",
          "Norasmiy va hurmatli shakllar farqini tushundim",
          "Egalik olmoshlarini bilaman",
        ],
      },
    ],
  },
  {
    id: 6,
    emoji: "\ud83c\udf5c",
    title: "Oziq-ovqat va Restoran",
    subtitle: "\uc74c\uc2dd\uacfc \uc2dd\ub2f9",
    color: "#ef4444",
    light: "#fef2f2",
    sections: [
      {
        type: "info",
        title: "\ud83d\udccc Dars maqsadi",
        items: [
          "Asosiy kores taomlarini o'rganish",
          "Restoranda buyurtma berishni o'rganish",
          "Ta'm va afzalliklar haqida gaplashishni o'rganish",
        ],
      },
      {
        type: "table",
        title: "1. Mashhur kores taomlar\u0131",
        headers: ["Kores", "Talaffuz", "Izoh"],
        rows: [
          ["\ube44\ube54\ubc25", "bibimbap", "Sabzavot va guruch aralashmasi"],
          ["\ubd88\uace0\uae30", "bulgogi", "Marinadlangan mol go'shti"],
          ["\uc0bc\uacb9\uc0b4", "samgyeopsal", "Cho'chqa qovurg'asi"],
          ["\uae40\uce58", "kimchi", "Achchiq fermentlangan sabzavot"],
          ["\ub5a1\ubcf6\uc774", "tteokbokki", "Achchiq guruch pirog"],
          ["\ub77c\uba74", "ramyon", "Tez pishiriladigan lapsha"],
          ["\uae40\uce58\ucc0c\uac1c", "kimchi jjigae", "Kimchi bilan sho'rva"],
          ["\uc21c\ub450\ubd80\ucc0c\uac1c", "sundubu jjigae", "Yumshoq tofu bilan sho'rva"],
          ["\ubcf6\uc74c\ubc25", "bokkeumbap", "Qovurilgan guruch"],
          ["\ub0c9\uba74", "naengmyeon", "Sovuq lapsha \u2014 yozgi taom"],
        ],
      },
      {
        type: "dialog",
        title: "2. Restoran dialogi",
        lines: [
          { speaker: "Mijoz", text: "\uc5ec\uae30\uc694!", translation: "Kechirasiz! (Ofitsiantni chaqirish)" },
          { speaker: "Ofitsiant", text: "\ub124, \uc8fc\ubb38\ud558\uc2dc\uaca0\uc5b4\uc694?", translation: "Ha, buyurtma berasizmi?" },
          { speaker: "Mijoz", text: "\ube44\ube54\ubc25 \ud558\ub098\ub791 \ubb3c \uc8fc\uc138\uc694.", translation: "Bir bibimbap va suv bering." },
          { speaker: "Ofitsiant", text: "\ub124, \uc7a0\uae50\ub9cc\uc694.", translation: "Ha, bir daqiqa." },
          { speaker: "Mijoz", text: "\uacc4\uc0b0\ud574 \uc8fc\uc138\uc694.", translation: "Hisob-kitob qiling." },
        ],
      },
      {
        type: "table",
        title: "3. Ta'm sifatlari",
        headers: ["Kores", "Talaffuz", "Ma'nosi"],
        rows: [
          ["\ub9db\uc788\uc5b4\uc694", "masiseoyo", "mazali"],
          ["\ub9db\uc5c6\uc5b4\uc694", "madeopsseoyo", "mazasiz"],
          ["\ub9e4\uc6cc\uc694", "maeweoyo", "achimsiq"],
          ["\ub2ec\uc544\uc694", "darayo", "shirin"],
          ["\uc9dc\uc694", "jjayo", "sho'r"],
          ["\uc154\uc694", "syeoyo", "nordon"],
          ["\uace0\uc18c\ud574\uc694", "gosohaeyo", "yog'li-yoqimli"],
        ],
      },
      {
        type: "check",
        title: "\u2705 Nazorat savollari",
        items: [
          "10 ta kores taomini bilaman",
          "Restoranda buyurtma bera olaman",
          "Ta'm so'zlarini bilaman",
          "Hisob so'rashni bilaman",
        ],
      },
    ],
  },
  {
    id: 7,
    emoji: "\ud83d\uddfa\ufe0f",
    title: "Yo'nalish va Transport",
    subtitle: "\uae38 \uc548\ub0b4\uc640 \uad50\ud1b5",
    color: "#0891
